services:
  postgres:
    image: 'postgres:16'
    container_name: dashboard-db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - 'POSTGRES_DB=dokkcorp_db'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G # Plus de cache pour Postgres
    networks:
      - dashboard-network

  backend:
    image: ${DOCKER_USERNAME}/dashboard-backend:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: dashboard-backend
    restart: always
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}
      - BLOCKCHAIN_RPC_URL=${BLOCKCHAIN_RPC_URL}
      - FMP_API_KEY=${FMP_API_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
    ports:
      - '127.0.0.1:8080:8080'
    deploy:
      resources:
        limits:
          memory: 1.5G # Marge pour le container Java
    networks:
      - dashboard-network

  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: watchtower
    restart: always
    environment:
      - DOCKER_API_VERSION=1.41
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 3600 --cleanup --label-enable
    deploy:
      resources:
        limits:
          memory: 100M
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge

volumes:
  postgres_data:
