asset-id: brwm
forward-dividend: 0.25
forward-dividend-currency: GBP
frequency: quarterly
avg-dividend-growth-10y: 7.0
history:
  - { year: 2025, amount: 0.24, currency: GBP }
  - { year: 2024, amount: 0.23, currency: GBP }
  - { year: 2023, amount: 0.335, currency: GBP }
  - { year: 2022, amount: 0.40, currency: GBP }
  - { year: 2021, amount: 0.425, currency: GBP }
  - { year: 2020, amount: 0.203, currency: GBP }
  - { year: 2019, amount: 0.22, currency: GBP }
  - { year: 2018, amount: 0.18, currency: GBP }
  - { year: 2017, amount: 0.156, currency: GBP }
  - { year: 2016, amount: 0.13, currency: GBP }
