asset-id: inveb
forward-dividend: 6.00
forward-dividend-currency: SEK
frequency: annual
avg-dividend-growth-10y: 8.2
history:
  - { year: 2024, amount: 6.00, currency: SEK }
  - { year: 2023, amount: 5.50, currency: SEK }
  - { year: 2022, amount: 4.00, currency: SEK }
